/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Track = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'album' : IDL.Text,
  'artist' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlaylistData = IDL.Record({
  'owner' : IDL.Principal,
  'tracks' : IDL.Vec(Track),
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const CloudData = IDL.Record({
  'playlists' : IDL.Vec(IDL.Tuple(IDL.Text, PlaylistData)),
  'favorites' : IDL.Vec(IDL.Text),
  'history' : IDL.Vec(IDL.Text),
  'profile' : IDL.Opt(UserProfile),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToHistory' : IDL.Func([IDL.Text], [], []),
  'addTrackToPlaylist' : IDL.Func([IDL.Text, Track], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearHistory' : IDL.Func([], [], []),
  'createPlaylist' : IDL.Func([IDL.Text], [], []),
  'deletePlaylist' : IDL.Func([IDL.Text], [], []),
  'exportCloudData' : IDL.Func([], [CloudData], []),
  'getAllPlaylists' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(Track))], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'renamePlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleFavorite' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Track = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'album' : IDL.Text,
    'artist' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlaylistData = IDL.Record({
    'owner' : IDL.Principal,
    'tracks' : IDL.Vec(Track),
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const CloudData = IDL.Record({
    'playlists' : IDL.Vec(IDL.Tuple(IDL.Text, PlaylistData)),
    'favorites' : IDL.Vec(IDL.Text),
    'history' : IDL.Vec(IDL.Text),
    'profile' : IDL.Opt(UserProfile),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToHistory' : IDL.Func([IDL.Text], [], []),
    'addTrackToPlaylist' : IDL.Func([IDL.Text, Track], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearHistory' : IDL.Func([], [], []),
    'createPlaylist' : IDL.Func([IDL.Text], [], []),
    'deletePlaylist' : IDL.Func([IDL.Text], [], []),
    'exportCloudData' : IDL.Func([], [CloudData], []),
    'getAllPlaylists' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getPlaylist' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Vec(Track))], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeTrackFromPlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'renamePlaylist' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleFavorite' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };