/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Track {
  'id' : string,
  'title' : string,
  'album' : string,
  'artist' : string,
}
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToHistory' : ActorMethod<[string], undefined>,
  'addTrackToPlaylist' : ActorMethod<[string, Track], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearHistory' : ActorMethod<[], undefined>,
  'createPlaylist' : ActorMethod<[string], undefined>,
  'deletePlaylist' : ActorMethod<[string], undefined>,
  'getAllPlaylists' : ActorMethod<[], Array<string>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<string>>,
  'getHistory' : ActorMethod<[], Array<string>>,
  'getPlaylist' : ActorMethod<[string], [] | [Array<Track>]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeTrackFromPlaylist' : ActorMethod<[string, string], undefined>,
  'renamePlaylist' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleFavorite' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];